[package]
name = "cng4"
version = "0.1.1"
edition = "2024"

[dependencies]
actix-web = "4"
chrono = "0.4.42"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
