[package]
name = "cng4"
version = "0.1.2"
edition = "2024"

[dependencies]
actix-web = "4"
async-trait = "0.1.89"
chrono = "0.4.42"
clap = { version = "4", features = ["derive"] }
log = "0.4.28"
serde = { version = "1", features = ["derive"] }
shell-words = "1.1.0"
sysinfo = "0.37.0"
tokio = { version = "1", features = ["full"] }
toml = "0.9.7"
