name = "cng4"

script_gui = """
# Custom GUI script
p plugins insert cli
p plugins insert system
p plugins show
p cfg show
p system show
"""

script_cli = """
# Custom CLI script
p plugins show
p cfg show
p system show
"""
