name = "cng4"

script_gui = """
# Custom GUI script

# for GUI mode
p plugins insert panels

# - log
p panels create log log 0 0 50 60
p log gui log

p plugins insert system
p plugins insert devices

# - mqtt
p plugins insert mqtt
p panels create mqtt mqtt 51 0 50 60
p mqtt gui mqtt
p mqtt restart

# - plugins
p plugins insert web
p plugins insert music

# - gui
p panels create command gui 0 0 80 3
p plugins insert gui
"""

script_cli = """
# Custom CLI script

p plugins insert system
p plugins insert devices

# - mqtt
p plugins insert mqtt
p mqtt restart

p plugins insert web
p plugins insert music

# - cli
p plugins insert cli
"""
