name = "cng4"

script_gui = """
# Custom GUI script
p plugins insert system
p plugins insert web
p plugins insert music
p plugins insert cli
"""

script_cli = """
# Custom CLI script
p plugins insert system
p plugins insert web
p plugins insert music
p plugins insert cli
"""
