script_gui = """
# Custom GUI script

# - command
#   - put it first
p plugins insert command
p command gui normal 0 0 80 3

# - log
p log gui normal 0 0 70 60

# - plugins
p plugins insert system
p plugins insert devices

# - mqtt
p plugins insert mqtt
p mqtt gui normal 71 0 30 60
p mqtt restart

# - infos
p plugins insert infos
# p plugins panel create infos infos normal 0 61 100 40
p infos gui normal 0 61 100 40

# - weather
p plugins insert weather
p weather gui infos
p weather add 新店 24.9676 121.542
p weather add 新莊 25.0359 121.45
p weather add 台北 25.0330 121.5654
p weather add 台南 23.1725 120.279
p weather add Eindhoven 51.44 5.46
p weather add 東京 35.6895 139.6917
p weather add 西雅圖 47.6062 122.3321
p weather add 清邁 18.7061 98.9817
p weather add 拜縣 19.3583 98.4418

# - plugins
p plugins insert web
p plugins insert music

# - editor
p plugins insert editor
p editor gui popup 10 10 80 80

# - wol
p plugins insert wol
p wol add linds 90:09:d0:64:4e:a4

p plugins insert gui
"""

script_cli = """
# Custom CLI script

# - plugins
p plugins insert system
p plugins insert devices

# - mqtt
p plugins insert mqtt
p mqtt restart

# - weather
p plugins insert weather
p weather add 新店 24.9676 121.542
p weather add 新莊 25.0359 121.45
p weather add 台北 25.0330 121.5654
p weather add 台南 23.1725 120.279
p weather add Eindhoven 51.44 5.46
p weather add 東京 35.6895 139.6917
p weather add 西雅圖 47.6062 122.3321
p weather add 清邁 18.7061 98.9817
p weather add 拜縣 19.3583 98.4418

p plugins insert web
p plugins insert music

# - wol
p plugins insert wol
p wol add linds 90:09:d0:64:4e:a4

# - cli
p plugins insert cli
"""
