script_gui = """
# Custom GUI script

# for GUI mode
p plugins insert panels

# - gui
p panels create command gui 0 0 80 3
p plugins insert gui

# - log
p panels create log log 0 0 50 60
p log gui log

# - plugins
p plugins insert system
p plugins insert devices

# - mqtt
p plugins insert mqtt
p panels create mqtt mqtt 51 0 50 60
p mqtt gui mqtt
p mqtt restart

# - weather
p plugins insert weather
p weather gui infos
p weather add 新店 24.9676 121.542
p weather add 新莊 25.0359 121.45
p weather add 台北 25.0330 121.5654
p weather add 台南 23.1725 120.279
p weather add Eindhoven 51.44 5.46
p weather add 東京 35.6895 139.6917
p weather add 西雅圖 47.6062 122.3321
p weather add 清邁 18.7061 98.9817
p weather add 拜縣 19.3583 98.4418

# - infos
p plugins insert infos
p panels create infos infos 0 61 100 40
p infos gui infos

# - plugins
p plugins insert web
p plugins insert music
"""

script_cli = """
# Custom CLI script

# - plugins
p plugins insert system
p plugins insert devices

# - mqtt
p plugins insert mqtt
p mqtt restart

# - weather
p plugins insert weather
p weather add 新店 24.9676 121.542
p weather add 新莊 25.0359 121.45
p weather add 台北 25.0330 121.5654
p weather add 台南 23.1725 120.279
p weather add Eindhoven 51.44 5.46
p weather add 東京 35.6895 139.6917
p weather add 西雅圖 47.6062 122.3321
p weather add 清邁 18.7061 98.9817
p weather add 拜縣 19.3583 98.4418

p plugins insert web
p plugins insert music

# - cli
p plugins insert cli
"""
